# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

name: WebFiles Pipes

trigger:
- master
- azure*

pr:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build_and_Pack
  jobs:
  - job: install
    steps: 
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'
    - script: npm install

  - job: build
    dependsOn: install
    steps:
    - script: npm run build
    - script: ls -la
      
  - job: pack
    dependsOn: build
    steps:
      - script: npm run pack 
